baseURL = "https://pandemicpregnancy.com/"
languageCode = "en-us"
title = "Pandemic Pregnancy"
enableRobotsTXT = true
googleAnalytics = "UA-105680531-6"
metaDataFormat = "toml"

enableGitInfo = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[markup.goldmark.renderer]
unsafe = true

[params]
  author = "Jack Cary"
  description = "Resetting expectations in the time of COVID-19"

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

[[menu.main]]
  identifier = "resources"
  name = "Resources"
  title = "Resources"
  url = "/resources/"
  weight = 100

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About"
  url = "/about/"
  weight = 200
